// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Dumont.Triage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Dumont.Triage;

[GenerateTypedNameReferences]
public sealed partial class TriageTaggerWindow : DefaultWindow
{
    /// <summary>
    /// Prioridade escolhida pelo jogador. Nulo é o botão de tirar a marcação.
    /// </summary>
    public event Action<ProtoId<TriageIconPrototype>?>? OnLevelPicked;

    public TriageTaggerWindow()
    {
        RobustXamlLoader.Load(this);

        ClearButton.OnPressed += _ => OnLevelPicked?.Invoke(null);
    }

    public void Update(string patient, IReadOnlyList<TriageIconPrototype> levels, ProtoId<TriageIconPrototype>? current)
    {
        PatientLabel.Text = patient;
        ClearButton.Disabled = current == null;

        LevelsContainer.RemoveAllChildren();

        foreach (var level in levels)
        {
            LevelsContainer.AddChild(BuildRow(level, current?.Id == level.ID));
        }
    }

    private Control BuildRow(TriageIconPrototype level, bool active)
    {
        var swatch = new PanelContainer
        {
            MinSize = new Vector2(8, 0),
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = level.Color },
        };

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        text.AddChild(new Label { Text = Loc.GetString(level.Name) });
        text.AddChild(new Label
        {
            Text = Loc.GetString(level.Description),
            StyleClasses = { "LabelSubText" },
        });

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };

        row.AddChild(swatch);
        row.AddChild(text);

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            Disabled = active,
            StyleClasses = { ContainerButton.StyleClassButton },
        };

        button.AddChild(row);
        button.OnPressed += _ => OnLevelPicked?.Invoke(new ProtoId<TriageIconPrototype>(level.ID));

        return button;
    }
}
