# SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
# SPDX-FileCopyrightText: 2025 OttavioBasques <otaviobasques@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Gabystation/Andromeda

- type: latheRecipePack
  id: SecurityPowerguns
  recipes:
  - WeaponRifleMA56XF
  - WeaponPistolMX3R
  - WeaponShotgunAntelope

- type: latheRecipePack
  id: SecurityModules
  recipes:
  - ModsuitModuleSecHudRecipe
  - ModsuitModuleInjectorRecipe
  - ModsuitPlatingSecurityRecipe

- type: latheRecipePack
  id: SecurityClothing
  recipes:
  - SecurityMagbootsRecipe
