// SPDX-FileCopyrightText: 2026 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2026 GabyChangelog <agentepanela2@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Content.Shared._Gabystation.ServerCurrency.Prototypes;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using Robust.Shared.Timing;
using Robust.Client.UserInterface;
using System.Numerics;
using Content.Goobstation.Common.ServerCurrency;
using Robust.Client.GameObjects;
using Content.Shared._Gabystation.ServerCurrency.UI;

namespace Content.Client._Gabystation.ServerCurrency.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostStoreTab : BoxContainer
{
    [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<ProtoId<GhostSkinListingPrototype>>? OnBuy;
    public event Action<string>? ShowConfirm;

    private Dictionary<Button, (DateTime LastClick, GhostSkinListingPrototype Listing)> _buttonClickTimes = new();
    public List<ProtoId<GhostSkinListingPrototype>> Owned = new List<ProtoId<GhostSkinListingPrototype>>();

    private const double DoubleClickTimeWindow = 1.5; // seconds

    public GhostStoreTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateTokenButtons();
        UpdateButtonStates();
    }

    public void UpdateState(CurrencyEuiState state)
    {
        Owned = state.OwnedGhostSkins;
        PopulateTokenButtons(); // recreate all buttons
        UpdateButtonStates();
    }

    private void PopulateTokenButtons()
    {
        GhostListingsContainer.DisposeAllChildren();
        _buttonClickTimes.Clear();

        var spriteSys = _entMan.System<SpriteSystem>();

        var titleListings = _protoManager.EnumeratePrototypes<GhostSkinListingPrototype>()
            .Where(x => x.Available)
            .OrderBy(x => x.Price);

        foreach (var listing in titleListings)
        {
            var rawTitle = Loc.GetString(listing.Name);
            var box = new BoxContainer()
            {
                Orientation = LayoutOrientation.Horizontal,
            };
            var texture = new TextureRect()
            {
                Texture = spriteSys.Frame0(listing.Sprite),
                Stretch = TextureRect.StretchMode.KeepAspect,
                MinSize = new Vector2(64, 64),
                MaxSize = new Vector2(64, 64),
            };
            var button = new Button
            {
                Text = Loc.GetString("gs-balanceui-shop-buy-ghost-skin-btn", ("title", rawTitle), ("price", listing.Price)),
                MinHeight = 64,
                HorizontalExpand = true,
            };

            box.AddChild(texture);
            box.AddChild(button);

            if (listing.Color is not null)
            {
                button.Modulate = Color.FromHex(listing.Color);
                texture.Modulate = Color.FromHex(listing.Color);
            }

            if (Owned.Contains(listing.ID))
            {
                button.Disabled = true;
                button.Text = Loc.GetString("gs-balanceui-shop-buy-ghost-skin-owned", ("title", rawTitle));
                GhostListingsContainer.AddChild(box);
                GhostListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
                continue;
            }

            button.OnPressed += _ =>
            {
                if (_buttonClickTimes.TryGetValue(button, out var clickData))
                {
                    var timeSinceLastClick = (DateTime.Now - clickData.LastClick).TotalSeconds;
                    if (timeSinceLastClick <= DoubleClickTimeWindow)
                    {
                        // Double click occurred
                        OnBuy?.Invoke(listing.ID);
                        ShowConfirm?.Invoke(Loc.GetString(listing.Name));
                        _buttonClickTimes.Remove(button);
                        button.Text = Loc.GetString("gs-balanceui-shop-buy-ghost-skin-btn", ("title", rawTitle), ("price", listing.Price));
                        return;
                    }
                }

                // First click
                _buttonClickTimes[button] = (DateTime.Now, listing);
                button.Text = Loc.GetString("gs-balanceui-shop-click-confirm");

                // Reset button text after delay
                Timer.Spawn(TimeSpan.FromSeconds(DoubleClickTimeWindow), () =>
                {
                    if (_buttonClickTimes.ContainsKey(button))
                    {
                        button.Text = Loc.GetString("gs-balanceui-shop-buy-ghost-skin-btn", ("title", rawTitle), ("price", listing.Price));
                        _buttonClickTimes.Remove(button);
                        if (listing.Color is not null)
                            button.Modulate = Color.FromHex(listing.Color);
                        UpdateButtonStates();
                    }
                });
            };

            GhostListingsContainer.AddChild(box);
            GhostListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
        }
    }

    public void UpdateButtonStates(int? balance = null)
    {
        if (balance == null)
            balance = _serverCur.GetBalance();

        //Header.Text = _serverCur.Stringify(balance.Value);
        foreach (var child in GhostListingsContainer.Children)
        {
            if (child is not BoxContainer box)
                continue;

            foreach (var bChild in box.Children)
            {
                if (bChild is not Button button)
                    continue;

                var listing = _protoManager.EnumeratePrototypes<GhostSkinListingPrototype>()
                    .FirstOrDefault(x => Loc.GetString("gs-balanceui-shop-buy-ghost-skin-btn", ("title", Loc.GetString(x.Name)), ("price", x.Price)) == button.Text);

                if (listing is not null)
                    button.Disabled = balance < listing.Price;
            }
        }
    }
}
