// SPDX-FileCopyrightText: 2026 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2026 GabyChangelog <agentepanela2@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Content.Shared._Gabystation.ServerCurrency.Prototypes;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using Robust.Shared.Timing;
using Robust.Client.UserInterface;
using System.Numerics;
using Content.Goobstation.Common.ServerCurrency;
using Robust.Shared.Utility;
using Content.Shared._Gabystation.ServerCurrency.UI;

namespace Content.Client._Gabystation.ServerCurrency.UI;

[GenerateTypedNameReferences]
public sealed partial class TitleStoreTab : BoxContainer
{
    [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    public event Action<ProtoId<TitleListingPrototype>>? OnBuy;
    public event Action<string>? ShowConfirm;

    private Dictionary<Button, (DateTime LastClick, TitleListingPrototype Listing)> _buttonClickTimes = new();
    public List<ProtoId<TitleListingPrototype>> Owned = new List<ProtoId<TitleListingPrototype>>();

    private const double DoubleClickTimeWindow = 1.5; // seconds

    public TitleStoreTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateTokenButtons();
        UpdateButtonStates();
    }

    public void UpdateState(CurrencyEuiState state)
    {
        Owned = state.OwnedTitles;
        PopulateTokenButtons(); // recreate all buttons
        UpdateButtonStates();
    }

    private void PopulateTokenButtons()
    {
        TitleListingsContainer.DisposeAllChildren();
        _buttonClickTimes.Clear();

        var titleListings = _protoManager.EnumeratePrototypes<TitleListingPrototype>()
            .Where(x => x.Available)
            .OrderBy(x => x.Price);

        foreach (var listing in titleListings)
        {
            var rawTitle = FormattedMessage.RemoveMarkupOrThrow(Loc.GetString(listing.Title));
            var button = new Button
            {
                Text = Loc.GetString("gs-balanceui-shop-buy-title-btn", ("title", rawTitle), ("price", listing.Price)),
                MinHeight = 40,
            };

            if (Owned.Contains(listing.ID))
            {
                button.Disabled = true;
                button.Text = Loc.GetString("gs-balanceui-shop-buy-title-owned", ("title", rawTitle));
                TitleListingsContainer.AddChild(button);
                TitleListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
                continue;
            }

            // Custom colors with disabled btn dont work well
            if (listing.Color is not null)
                button.Modulate = Color.FromHex(listing.Color);

            button.OnPressed += _ =>
            {
                if (_buttonClickTimes.TryGetValue(button, out var clickData))
                {
                    var timeSinceLastClick = (DateTime.Now - clickData.LastClick).TotalSeconds;
                    if (timeSinceLastClick <= DoubleClickTimeWindow)
                    {
                        // Double click occurred
                        OnBuy?.Invoke(listing.ID);
                        ShowConfirm?.Invoke(Loc.GetString(listing.Title));
                        _buttonClickTimes.Remove(button);
                        button.Text = Loc.GetString("gs-balanceui-shop-buy-title-btn", ("title", rawTitle), ("price", listing.Price));
                        return;
                    }
                }

                // First click
                _buttonClickTimes[button] = (DateTime.Now, listing);
                button.Text = Loc.GetString("gs-balanceui-shop-click-confirm");

                // Reset button text after delay
                Timer.Spawn(TimeSpan.FromSeconds(DoubleClickTimeWindow), () =>
                {
                    if (_buttonClickTimes.ContainsKey(button))
                    {
                        button.Text = Loc.GetString("gs-balanceui-shop-buy-title-btn", ("title", rawTitle), ("price", listing.Price));
                        _buttonClickTimes.Remove(button);
                        if (listing.Color is not null)
                            button.Modulate = Color.FromHex(listing.Color);
                        UpdateButtonStates();
                    }
                });
            };

            TitleListingsContainer.AddChild(button);
            TitleListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
        }
    }

    public void UpdateButtonStates(int? balance = null)
    {
        if (balance is null)
            balance = _serverCur.GetBalance();

        //Header.Text = _serverCur.Stringify(balance.Value);
        foreach (var child in TitleListingsContainer.Children)
        {
            if (child is not Button button)
                continue;

            var listing = _protoManager.EnumeratePrototypes<TitleListingPrototype>()
                .FirstOrDefault(x => Loc.GetString("gs-balanceui-shop-buy-title-btn", ("title", FormattedMessage.FromMarkupOrThrow(Loc.GetString(x.Title))), ("price", x.Price)) == button.Text);

            if (listing is not null)
                button.Disabled = balance < listing.Price;
        }
    }
}
