// SPDX-FileCopyrightText: 2026 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2026 GabyChangelog <agentepanela2@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Goobstation.Common.ServerCurrency;
using System.Linq;
using Robust.Shared.Timing;
using Robust.Client.UserInterface;
using System.Numerics;
using Content.Shared._Gabystation.ServerCurrency.UI;
using Content.Shared._Gabystation.ServerCurrency.Prototypes;

namespace Content.Client._Gabystation.ServerCurrency.UI;

[GenerateTypedNameReferences]
public sealed partial class TokenStoreTab : BoxContainer
{
    [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    public event Action<ProtoId<TokenListingPrototype>>? OnBuy;
    public event Action<string>? ShowConfirm;

    private IOrderedEnumerable<TokenListingPrototype> _storeStorage;
    private Dictionary<Button, (DateTime LastClick, TokenListingPrototype Listing)> _buttonClickTimes = new();

    private const double DoubleClickTimeWindow = 1.5; // seconds
    public float Cooldown = 0f;
    
    public TokenStoreTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _storeStorage = Enumerable.Empty<TokenListingPrototype>().OrderBy(x => 0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        RotationCooldown.Text = Loc.GetString("gs-balanceui-shop-cooldown", ("cooldown", FormatCooldown(Cooldown)));
    }

    private static string FormatCooldown(float seconds)
    {
        var time = TimeSpan.FromSeconds(seconds);

        if (time.TotalHours >= 1)
            return $"{time.Hours}h {time.Minutes}m {time.Seconds}s";

        if (time.TotalMinutes >= 1)
            return $"{time.Minutes}m {time.Seconds}s";

        return $"{time.Seconds}s";
    }

    public void UpdateState(CurrencyEuiState state)
    {
        Cooldown = state.Cooldown;

        _storeStorage = state.Tokens
            .Select(id =>
            {
                _protoManager.TryIndex(id, out TokenListingPrototype? proto);
                return proto;
            })
            .OfType<TokenListingPrototype>()
            .OrderByDescending(p => p.Price);

        PopulateTokenButtons();
        UpdateButtonStates();
    }

    public string GetTokenBtnText(TokenListingPrototype listing)
    {
        var name = Loc.GetString("gs-balanceui-shop-buy-btn",
                        ("token", Loc.GetString(listing.Name)), ("price", listing.Price));

        if (listing.Type == "Antag")
        {
            var tokenStr = Loc.GetString("gs-balanceui-shop-token-antag-buy", ("token", Loc.GetString(listing.Name)));
            name = Loc.GetString("gs-balanceui-shop-buy-btn",
                        ("token", tokenStr), ("price", listing.Price));
        }
        if (listing.Type == "GhostRole")
        {
            var tokenStr = Loc.GetString("gs-balanceui-shop-token-ghost-role-buy", ("token", Loc.GetString(listing.Name)));
            name = Loc.GetString("gs-balanceui-shop-buy-btn",
                        ("token", tokenStr), ("price", listing.Price));
        }

        return name;
    }

    public void PopulateTokenButtons()
    {
        TokenListingsContainer.DisposeAllChildren();
        _buttonClickTimes.Clear();

        foreach (var listing in _storeStorage)
        {
            var toolTip = "u are not able to see this";
            if (listing.Type == "Antag")
                toolTip = Loc.GetString("gs-balanceui-shop-token-antag-desc", ("token", Loc.GetString(listing.Name)));
            else if (listing.Type == "GhostRole")
                toolTip = Loc.GetString("gs-balanceui-shop-token-ghost-role-desc", ("token", Loc.GetString(listing.Name)));
            else
                toolTip = Loc.GetString(listing.Description);

            var button = new Button
            {
                Text = GetTokenBtnText(listing),
                MinHeight = 40,
                ToolTip = toolTip
            };

            SetupButton(button, listing);

            TokenListingsContainer.AddChild(button);
            TokenListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
        }
    }

    // Gaby change
    public void SetupButton(Button button, TokenListingPrototype listing)
    {
        button.OnPressed += _ =>
        {
            if (_buttonClickTimes.TryGetValue(button, out var clickData))
            {
                var timeSinceLastClick = (DateTime.Now - clickData.LastClick).TotalSeconds;
                if (timeSinceLastClick <= DoubleClickTimeWindow)
                {
                    // Double click occurred
                    OnBuy?.Invoke(listing.ID);
                    ShowConfirm?.Invoke(Loc.GetString(listing.Name));
                    _buttonClickTimes.Remove(button);
                    button.Text = GetTokenBtnText(listing);
                    return;
                }
            }

            // First click
            _buttonClickTimes[button] = (DateTime.Now, listing);
            button.Text = Loc.GetString("gs-balanceui-shop-click-confirm");

            // Reset button text after delay
            Timer.Spawn(TimeSpan.FromSeconds(DoubleClickTimeWindow), () =>
            {
                if (_buttonClickTimes.ContainsKey(button))
                {
                    button.Text = GetTokenBtnText(listing);
                    _buttonClickTimes.Remove(button);
                    UpdateButtonStates();
                }
            });
        };
    }

    public void UpdateButtonStates(int? balance = null)
    {
        if (balance is null)
            balance = _serverCur.GetBalance();

        //Header.Text = _serverCur.Stringify(balance.Value);
        foreach (var child in TokenListingsContainer.Children)
        {
            if (child is not Button button)
                continue;

            // Gaby change - I dont like the way this works
            var listing = _storeStorage.FirstOrDefault(x =>
                GetTokenBtnText(x) == button.Text);

            if (listing is not null)
                button.Disabled = balance < listing.Price;
        }
    }
}
