// SPDX-FileCopyrightText: 2023 MishaUnity <81403616+MishaUnity@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 DakotaGay <dakotagay@disroot.org>
// SPDX-FileCopyrightText: 2024 Julian Giebel <juliangiebel@live.de>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Client.UserInterface.RichText;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

// Goobstation ported Wizden
// https://github.com/space-wizards/space-station-14/pull/41799
//  Fix news console formatting #41799
[GenerateTypedNameReferences]
public sealed partial class NewsReaderUiFragment : BoxContainer
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;

    public event Action? OnNotificationSwithPressed;
    //Starlight-edit: start
    public event Action? OnLikeButtonPressed;
    public event Action? OnDislikeButtonPressed;
    //Starlight-edit: end

    private Type[] AllowedTags =
    [
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(HeadingTag),
        typeof(ItalicTag),
        typeof(MonoTag),
    ];

    public NewsReaderUiFragment()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnNotificationSwithPressed?.Invoke();
        // Starlight-edit: start
        Like.OnPressed += _ => OnLikeButtonPressed?.Invoke();
        Dislike.OnPressed += _ => OnDislikeButtonPressed?.Invoke();
        // Starlight-edit: end
    }

    public void UpdateState(NewsArticle article, int targetNum, int totalNum, bool notificationOn, bool hasReacted)
    {
        PageNum.Visible = true;
        PageText.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;
        // Starlight-edit: start
        Like.Visible = true;
        Dislike.Visible = true;
        Views.Visible = true;
        ReactionsSeparator.Visible = true;
        ViewsSeparator.Visible = true;
        // Starlight-edit: end

        PageName.Text = article.Title;
        PageText.SetMessage(FormattedMessage.FromMarkupPermissive(article.Content), AllowedTags);

        PageNum.Text = $"{targetNum}/{totalNum}";

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        var shareTime = article.ShareTime.ToString(@"hh\:mm\:ss");
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        var author = Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author ?? Loc.GetString("news-read-ui-no-author"));
        Author.SetMessage(FormattedMessage.FromMarkupPermissive(author), AllowedTags);
        // Starlight-edit: start
        LikeCountLabel.Text = Loc.GetString("news-read-ui-like-text", ("count", article.Likes));
        DislikeCountLabel.Text = Loc.GetString("news-read-ui-dislike-text", ("count", article.Dislikes));
        Views.SetMarkup(Loc.GetString("news-read-ui-views-text", ("count", article.Views)));

        Like.Disabled = hasReacted;
        Dislike.Disabled = hasReacted;
        // Starlight-edit: end
        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;
    }

    public void UpdateEmptyState(bool notificationOn)
    {
        PageNum.Visible = false;
        PageText.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;
        // Starlight-edit: start
        Like.Visible = false;
        Dislike.Visible = false;
        Views.Visible = false;
        ReactionsSeparator.Visible = false;
        ViewsSeparator.Visible = false;
        Like.Disabled = false;
        Dislike.Disabled = false;
        // Starlight-edit: end
        PageName.Text = Loc.GetString("news-read-ui-not-found-text");

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");
    }
}
