// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.ADT.Shuttles;

[GenerateTypedNameReferences]
public sealed partial class DropPodConsoleWindow : FancyWindow
{
    public event Action<NetEntity>? OnDeployMessage;

    private List<DropPodBeaconInfo> _beacons = new();
    private NetEntity? _selectedBeacon;
    private string? _selectedBeaconName;

    private bool _canLaunch;
    private bool _alreadyLaunched;
    private int _tcBalance;
    private int _tcCost;

    public DropPodConsoleWindow()
    {
        RobustXamlLoader.Load(this);


        DeployButton.OnPressed += _ => OnDeployPressed();
    }

    public void UpdateState(DropPodConsoleBuiState s)
    {
        _beacons = s.ValidBeacons;
        _canLaunch = s.CanLaunch;
        _alreadyLaunched = s.AlreadyLaunched;
        _tcBalance = s.TcBalance;
        _tcCost = s.CurrentCost;


        if (s.IsAtWar)
        {
            if (s.WarCooldownRemaining > 0)
            {
                WarStatusLabel.Text = Loc.GetString("drop-pod-console-war-active", ("time", s.WarCooldownRemaining));
            }
            else
            {
                WarStatusLabel.Text = Loc.GetString("drop-pod-console-war-ready");
            }
            WarStatusLabel.FontColorOverride = Color.OrangeRed;
        }
        else
        {
            WarStatusLabel.Text = string.Empty;
        }


        if (s.StationGrid.HasValue)
        {
            var stationUid = IoCManager.Resolve<IEntityManager>().GetEntity(s.StationGrid.Value);
            if (MapControl.MapUid != stationUid)
            {
                MapControl.MapUid = stationUid;
                MapControl.ForceNavMapUpdate();
                MapControl.CenterOnWorldPos(stationUid, s.StationWorldCenter);
            }
        }


        if (_selectedBeacon.HasValue && !_beacons.Exists(b => b.Uid == _selectedBeacon.Value))
        {
            _selectedBeacon = null;
            _selectedBeaconName = null;
            MapControl.SetSelectedBeacon(null);
        }

        RebuildBeaconList();
        RefreshState();
    }

    private void RebuildBeaconList()
    {
        BeaconList.RemoveAllChildren();

        foreach (var beacon in _beacons)
        {
            var b = beacon;
            var btn = new Button
            {
                Text = b.Name,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
                Disabled = !_canLaunch || _alreadyLaunched,
                ModulateSelfOverride = _selectedBeacon == b.Uid ? Color.OrangeRed : null,
            };

            btn.OnPressed += _ => SelectBeacon(b.Uid, b.Name, b.WorldPos);
            BeaconList.AddChild(btn);
        }
    }

    private void SelectBeacon(NetEntity uid, string name, Vector2 worldPos)
    {
        if (!_canLaunch || _alreadyLaunched)
            return;

        _selectedBeacon = uid;
        _selectedBeaconName = name;
        MapControl.SetSelectedBeacon(worldPos);
        RefreshState();
    }

    private void RefreshState()
    {

        if (_alreadyLaunched)
        {
            StatusLabel.Text = Loc.GetString("drop-pod-console-status-launched");
            StatusLabel.FontColorOverride = Color.Gray;
        }
        else if (!_canLaunch)
        {
            StatusLabel.Text = Loc.GetString("drop-pod-console-status-not-ready");
            StatusLabel.FontColorOverride = Color.Yellow;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("drop-pod-console-status-ready");
            StatusLabel.FontColorOverride = Color.LimeGreen;
        }


        SelectedLabel.Text = _selectedBeaconName != null 
            ? _selectedBeaconName 
            : Loc.GetString("drop-pod-console-sector-none");
        SelectedLabel.FontColorOverride = _selectedBeaconName != null ? Color.OrangeRed : Color.Gray;


        TcLabel.Text = Loc.GetString("drop-pod-console-tc-label", ("balance", _tcBalance), ("cost", _tcCost));
        TcLabel.FontColorOverride = _tcBalance >= _tcCost ? Color.LimeGreen : Color.Red;


        DeployButton.Disabled = _selectedBeacon == null || !_canLaunch || _alreadyLaunched;

        if (!DeployButton.Disabled)
            DeployButton.ModulateSelfOverride = Color.Red;
        else
            DeployButton.ModulateSelfOverride = null;

        RebuildBeaconList();
    }

    private void OnDeployPressed()
    {
        if (_selectedBeacon == null)
            return;

        OnDeployMessage?.Invoke(_selectedBeacon.Value);
    }
}