// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Salvage;

[GenerateTypedNameReferences]
public sealed partial class SalvageMissionDisarmWindow : FancyWindow
{

    public Action<string>? SubmitCodeCallback;

    public SalvageMissionDisarmWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Input.PlaceHolder = Loc.GetString("salvage-mission-disarm-ui-menu-code-placeholder");
        Input.IsValid = s => int.TryParse(s, out var _);
        Input.OnTextChanged += OnTextChanged;
        SubmitButton.OnPressed += SubmitButtonPressed;
    }

    private void OnTextChanged(LineEdit.LineEditEventArgs obj) => 
        SubmitButton.Disabled = Input.Text == "";

    private void SubmitButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!int.TryParse(Input.Text, out var code))
            return;
        
        SubmitCodeCallback?.Invoke(Input.Text);
    }
}