# SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Morph
  name: ghost-role-information-morph-name
  objective: ghost-role-information-morph-description
  antagonist: true