// SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Genetics;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Humanoid;

namespace Content.Client._Wega.Genetics.Ui;

[GenerateTypedNameReferences]
public sealed partial class MorphismGenPanel : DefaultWindow
{
    [Dependency] private readonly IEntityNetworkManager _entityNetworkManager = default!;

    private NetEntity _targetUser;
    private MorphismMenuOpenedEvent? _lastState;

    private readonly List<MarkingCategories> _generalCategories;

    public MorphismGenPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _generalCategories = Enum.GetValues<MarkingCategories>()
            .Where(c => c != MarkingCategories.Hair && c != MarkingCategories.FacialHair)
            .ToList();

        Tabs.SetTabTitle(0, Loc.GetString("markings-category-Hair"));
        Tabs.SetTabTitle(1, Loc.GetString("markings-category-FacialHair"));
        Tabs.SetTabTitle(2, Loc.GetString("markings-category-Special"));
        Tabs.SetTabTitle(3, Loc.GetString("humanoid-appearance-body-tab"));

        SetupPicker(HairPicker, MarkingCategories.Hair);
        SetupPicker(FacialHairPicker, MarkingCategories.FacialHair);

        GeneralPicker.OnMarkingSelect += args => SendMarkingChange(GetSelectedCategory(), args.slot, args.id);
        GeneralPicker.OnColorChanged += args => SendColorChange(GetSelectedCategory(), args.slot, args.marking);
        GeneralPicker.OnSlotRemove += args => SendSlotChange(GetSelectedCategory(), MorphismSlotEvent.SlotAction.Remove, args);
        GeneralPicker.OnSlotAdd += delegate { SendSlotChange(GetSelectedCategory(), MorphismSlotEvent.SlotAction.Add); };

        foreach (var cat in _generalCategories)
        {
            CategorySelector.AddItem(Loc.GetString($"markings-category-{cat}"), (int)cat);
        }
        
        CategorySelector.OnItemSelected += OnCategorySelected;

        if (_generalCategories.Count > 0) 
            CategorySelector.SelectId((int)_generalCategories[0]);

        ApplySkinBtn.OnPressed += _ => SendBodyColor(MorphismChangeBodyColorEvent.BodyPart.Skin, SkinColorPicker.Color);
        ApplyEyeBtn.OnPressed += _ => SendBodyColor(MorphismChangeBodyColorEvent.BodyPart.Eye, EyeColorPicker.Color);
    }

    private void SetupPicker(SingleMarkingPicker picker, MarkingCategories cat)
    {
        picker.OnMarkingSelect += args => SendMarkingChange(cat, args.slot, args.id);
        picker.OnColorChanged += args => SendColorChange(cat, args.slot, args.marking);
        picker.OnSlotRemove += args => SendSlotChange(cat, MorphismSlotEvent.SlotAction.Remove, args);
        picker.OnSlotAdd += delegate { SendSlotChange(cat, MorphismSlotEvent.SlotAction.Add); };
    }

    private MarkingCategories GetSelectedCategory()
    {
        return (MarkingCategories)CategorySelector.SelectedId;
    }

    private void OnCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        CategorySelector.SelectId(args.Id);
        UpdateGeneralPicker((MarkingCategories)args.Id);
    }

    public void Initialize(MorphismMenuOpenedEvent state)
    {
        _targetUser = state.TargetUser;
        _lastState = state;

        UpdatePickerData(HairPicker, MarkingCategories.Hair, state);
        UpdatePickerData(FacialHairPicker, MarkingCategories.FacialHair, state);

        UpdateGeneralPicker(GetSelectedCategory());

        SkinColorPicker.Color = state.SkinColor;
        EyeColorPicker.Color = state.EyeColor;
    }

    private void UpdateGeneralPicker(MarkingCategories category)
    {
        if (_lastState == null) return;
        
        GeneralPicker.Category = category;
        UpdatePickerData(GeneralPicker, category, _lastState);
    }

    private void UpdatePickerData(SingleMarkingPicker picker, MarkingCategories cat, MorphismMenuOpenedEvent state)
    {
        var markings = state.Markings.TryGetCategory(cat, out var list) ? new List<Marking>(list) : new();
        var totalPoints = state.Markings.PointsLeft(cat) + markings.Count;
        
        picker.UpdateData(markings, state.Species, totalPoints);
    }

    private void SendMarkingChange(MarkingCategories cat, int slot, string id)
    {
        _entityNetworkManager.SendSystemNetworkMessage(new MorphismChangeMarkingEvent(_targetUser, cat, slot, id));
    }

    private void SendColorChange(MarkingCategories cat, int slot, Marking marking)
    {
        _entityNetworkManager.SendSystemNetworkMessage(new MorphismChangeMarkingColorEvent(_targetUser, cat, slot, new(marking.MarkingColors)));
    }

    private void SendSlotChange(MarkingCategories cat, MorphismSlotEvent.SlotAction action, int slot = 0)
    {
        _entityNetworkManager.SendSystemNetworkMessage(new MorphismSlotEvent(_targetUser, cat, action, slot));
    }

    private void SendBodyColor(MorphismChangeBodyColorEvent.BodyPart part, Color color)
    {
        _entityNetworkManager.SendSystemNetworkMessage(new MorphismChangeBodyColorEvent(_targetUser, part, color));
    }
}
